<?php

include_once('archimedes_moodle_site.features.inc');

/**
 * Implementation of hook_archimedes_server_plugins().
 */
function archimedes_moodle_site_archimedes_server_plugins() {
  return array(
    'moodle-module',
  );
}

/**
  * Implementation of hook_block().
  * @param string $op one of "list", "view", "save" and "configure"
  * @param integer $delta code to identify the block
  * @param array $edit only for "save" operation
  */
function archimedes_moodle_site_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    // Generate listing of blocks from this module, for the admin/block page
    $block = array();
    $block[0]['info'] = t('Moodle Modules');
    $block[1]['info'] = t('Moodle Growth');
    return $block;
  }
  elseif ($op == 'view') {

    $content = '';
    $subject = '';

    switch ($delta) {
      case 0:
        if (arg(0) == 'node' && is_numeric(arg(1))) {
          $node = node_load(arg(1));
          $content = archimedes_moodle_site_modules($node);
        }
        break;
      case 1:
        if(arg(0) == 'node' && is_numeric(arg(1)) && ! arg(2)) {
          $node = node_load(arg(1));

          // moodle growth graph
          $courses = $users = $times = $xdates = array();
          $query = db_query(sprintf("SELECT last_update.field_last_update_value AS timestamp, user_table.field_num_users_value AS users, content_moodle.field_mdl_num_courses_value AS courses FROM {content_field_last_update} last_update LEFT JOIN {content_field_num_users} user_table ON last_update.vid=user_table.vid LEFT JOIN {content_type_moodle} content_moodle ON last_update.vid=content_moodle.vid WHERE last_update.nid = %s  ORDER BY last_update.vid",$node->nid));
          while ($object = db_fetch_object($query)) {
            $courses[] = $object->courses;
            $users[] = $object->users;
            $times[] = (string) strtotime($object->timestamp);
          }

          $canvas = charts_graphs_get_graph('google-charts');
          $canvas->title = "Moodle Growth";
          $canvas->type = "line";
          $canvas->width = 600;
          $canvas->height = 300;
          $canvas->series = array(
            'Content' => $courses,
            'Users' => $users,
          );

          $i = 0;
          $formats = array('j', 'M', 'Y');
          while ($i < 3) {
            $xdates = array();
            foreach($times as $time) {
              $xdates[] = date($formats[$i],$time);
            }
            $xdates = array_unique ($xdates);
            if (count($xdates) < 15)
              break;
            $i++;
          }
          $canvas->x_labels = $xdates;

          $subject = t('Moodle Growth');
          $content = $canvas->get_chart();
        }
        break;
    }
  }
  $block['subject'] = $subject;
  $block['content'] = $content;
  return $block;
}

function archimedes_moodle_site_modules($node){
  if ($node->type == 'moodle') {
    $header = array('Module','Version','Instances');
    $vids = $node->field_mdl_mod;
    $modules = array();
    $result = db_query(sprintf("SELECT vid, instances FROM {archimedes_moodle_site_modules} WHERE nid = %d", $node->nid));
    $instances = array();
    while ($row = db_fetch_object($result)) {
      $instances[$row->vid] = $row->instances;
    }
    foreach($vids as $vid) {
      $vid = $vid['vid'];
      $module = node_load(array('type' => 'moodle_module'),$vid);
      $modules[] = array(l($module->title,'node/'.$module->nid),$module->field_mod_version[0]['value'],$instances[$vid]);
    }
    return theme('table',$header,$modules);
  }
}

function archimedes_moodle_site_type($node) {
  return $node->type == 'moodle';
}


function archimedes_moodle_site_archimedes_site_alter(&$node) {
  if (isset($node->field_mdl_mod)) {
    foreach ($node->field_mdl_mod as $field) {
      if($rid = db_result(db_query(sprintf("SELECT rid FROM {archimedes_moodle_site_modules} WHERE nid = %s AND vid = %d LIMIT 1", $node->nid, $field['vid'])))) {
        db_query(sprintf("UPDATE {archimedes_moodle_site_modules} set instances = %d WHERE rid = %d", $field['instances'], $rid));
      } else {
        db_query(sprintf("INSERT INTO {archimedes_moodle_site_modules} (nid, vid, instances) VALUES (%d, %d, %d)", $node->nid, $field['vid'], $field['instances']));
      }
    }
  }
}
