<?php
// $Id: charts_graphs_google_charts.module,v 1.1.2.1 2010/07/01 13:20:43 rsevero Exp $

/**
 * @file drupal module file implementing Google Charts charting.
 */

/**
  * Implementation of hook_chartgraph_provider().
  **/
function charts_graphs_google_charts_chartgraph_provider() {
  $provider = array(
    'path' => dirname(__FILE__) . '/charts_graphs_google_charts.class.inc', // must be full path
    'clazz' => 'ChartsGraphsGoogleCharts', // implementation class' name
    'name' => 'google-charts', // name used when invoking through a factory method
    'nice_name' => 'Google Charts',
    'chart_types' => array(
      'line' => t('Line'),
      'bar' => t('Bar'),
      'pie' => t('Pie'),
      'pie_3d' => t('3D Pie'),
      'area' => t('Area'),
      'side_bar' => t('Side Bar'),
      'stacked_side_bar' => t('Stacked Side Bar'),
      'queued_bar' => t('Queued Bar'),
      'stacked_bar' => t('Stacked Bar'),
    ),
  );

  return (object) $provider;
}
