<?php
// $Id: charts_graphs_open_flash.module,v 1.1.2.1 2010/07/01 20:59:33 rsevero Exp $

/**
* @file drupal module file implementing Open Charts Flash 2 charting.
*/

/**
 * Implementation of hook_chartgraph_provider().
 **/
function charts_graphs_open_flash_chartgraph_provider() {
  $provider =  array(
    'path' => dirname(__FILE__) . '/charts_graphs_open_flash.class.inc', //must be full path
    'clazz' => 'ChartsGraphsOpenFlash', //implementation class' name
    'name' => 'open-flash', //name used when invoking through a factroy method
    'nice_name' => 'Open Flash Charts 2',
    'chart_types' => array(
      'line' => t('Line'),
      'bar' => t('Bar'),
      'bar_3d' => t('3D Bar'),
      'bar_cylinder' => t('Cylinder Bar'),
      'bar_cylinder_outline' => t('Outlined Cylinder Bar'),
      'bar_dome' => t('Dome Bar'),
      'bar_filled' => t('Filled Bar'),
      'bar_glass' => t('Glass Bar'),
      'bar_round' => t('Glass Bar with rounded tops and bottoms'),
      'bar_round_glass' => t('Glass Bar with rounded tops'),
      'bar_sketch' => t('Sketched Bar'),
      'pie' => t('Pie'),
    ),
  );

  return (object) $provider;
}

function charts_graphs_open_flash_menu() {
  $items = array();

  $items['charts_graphs_open_flash/data'] = array(
    'page callback' => 'charts_graphs_open_flash_data',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * @param $cid
 *   cache_id from which cache to retrieve the data
 */
function charts_graphs_open_flash_data($cid = NULL) {
  $cache = cache_get($cid);
  if (!$cache) {
    drupal_not_found();
    exit();
  }
  $canvas = $cache->data;
    
  $chart = charts_graphs_get_graph('open-flash');
  
  $chart->get_data_from_cache($cid);

  drupal_json($chart);
  exit();
}
