<?php
// $Id: cmis_dev.module,v 1.2.4.11 2010/03/08 20:30:25 cbalan Exp $

/**
 * Implementation of hook_menu()
 */
function cmis_dev_menu() {
  $items['cmis/info'] = array(
    'type' => MENU_NORMAL_ITEM,
    'title' => t('CMIS Information'),
    'page callback' => 'cmis_dev_info',
    'access arguments' => array('administer site configuration'),
  );

  return $items;
}

/**
 * Return CMIS Repository Information such as repo name, repo description, 
 * vendor name, product name and product version.
 */
function cmis_dev_info() {
  module_load_include('api.inc', 'cmis');

  try {
    $repository = cmis_get_repository();
  }
  catch (CMISException $e) {
    cmis_error_handler('cmis_dev', $e);
    return '';
  }
    
  
  $rows = array();
  foreach($repository->info->repositoryInfo as $property_name => $property) {
    $rows[] = array(t($property_name), $property);
  }
  
  return theme('table', array(t('Name'), t('Properties')), $rows);
}