<?php
// $Id: reverse_node_reference.module,v 1.1.2.1 2010/05/13 14:29:19 markuspetrux Exp $

/**
 * @file
 * Enhances Views with reverse relationships for Node Reference fields.
 */

define('REVERSE_NODE_REFERENCE_MYSQL_MINIMUM', '5.1');

/**
 * Implementation of hook_views_api().
 */
function reverse_node_reference_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'reverse_node_reference') . '/views',
  );
}
