<?php
// $Id: alfresco_import.module,v 1.2.2.2 2010/04/26 12:33:02 xergius Exp $

/**
 * @file
 *
 */

/**
 * Implementation of hook_help().
 */
function alfresco_import_help($path, $arg) {

  switch ($path) {
    case 'alfresco/import':
      return '<p>'. t('Import multiple alfresco nodes from a space of Alfresco.') .'</p>';
    case 'admin/help#alfresco_import':
      return '<p>'. t('Allows importing multiple alfresco nodes from a space of Alfresco.') .'</p>';
  }
}

/**
 * Implementation of hook_perm().
 */
function alfresco_import_perm() {
  return array('import alfresco contents');
}

/**
 * Implementation of hook_menu().
 */
function alfresco_import_menu() {

  $items['alfresco/import'] = array(
    'title' => 'Import items',
    'description' => 'Import <em>Alfresco item</em> nodes from an Alfresco space.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('alfresco_import_form'),
    'access callback' => 'user_access',
    'access arguments' => array('import alfresco contents'),
    'file' => 'alfresco_import.pages.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  return $items;
}

/**
 * Implementation of hook_theme
 */
function alfresco_import_theme() {

  return array(
    'alfresco_import_table' => array(
      'arguments' => array('form' => NULL),
      'file' => 'alfresco_import.pages.inc',
    ),
  );
}
